version: '3'

services:
  db:
    image: japm/mongodb:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=dashboarduser
      - MONGODB_PASSWORD=dbpassword
      - MONGODB_DATABASE=dashboarddb
    volumes:
      - "db-data:/data/db"
      
  api:
    image: japm/hygieia-api
    depends_on:
     - db
    ports:
     - "8080:8080"

  ui:
   image: japm/hygieia-ui
   depends_on:
     - api
   ports:
     - "8088:80"

  phabricator-collector:
     image: japm/hygieia-phabricator-scm-collector
     depends_on:
       - db
     environment:
       - PHABRICATOR_HOST=<PHAB HOST>
       - PHABRICATOR_TOKEN=<PHAB TOKEN>
       - MONGO_PORT=tcp://db:27017
volumes:
  db-data: