apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.15.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: phabricator-collector
  name: phabricator-collector
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: phabricator-collector
    spec:
      containers:
      - env:
        - name: MONGO_PORT
          value: tcp://db:27017
        - name: PHABRICATOR_HOST
          value: <PHAB HOST>
        - name: PHABRICATOR_TOKEN
          value: <PHAB TOKEN>
        image: japm/hygieia-phabricator-scm-collector
        name: phabricator-collector
        resources: {}
      restartPolicy: Always
status: {}
